gx_camera_node:
  ros__parameters:
    device_sn: "KE0200060396" # 相机序列号；非空时按序列号选择设备
    device_index: 1 # 设备索引；未使用序列号时用于选择相机
    frame_id: "gx_camera_0_optical_frame" # 发布图像使用的光学坐标系
    image_topic: "/gx_camera_0/image_raw" # 原始图像话题
    camera_info_topic: "/gx_camera_0/camera_info" # 相机内参话题
    publish_rate: 100.0 # 图像发布频率（Hz）

    width: 1280 # 图像宽度（像素）
    height: 1024 # 图像高度（像素）

    gain: 12.0 # 手动增益
    auto_gain_max: 12.0 # 自动增益上限
    auto_gain_min: 2.0 # 自动增益下限
    auto_gain: 0 # 是否自动增益（0=关，非0=开）

    exposure_time: 2000.0 # 手动曝光时间（通常为微秒）
    auto_exposure_time_max: 10000.0 # 自动曝光上限
    auto_exposure_time_min: 1000.0 # 自动曝光下限
    auto_exposure: 0 # 是否自动曝光（0=关，非0=开）

    red_balance_ratio: 1.2000 # 红通道白平衡倍率
    green_balance_ratio: 1.0 # 绿通道白平衡倍率
    blue_balance_ratio: 1.2800 # 蓝通道白平衡倍率
    auto_balance_mode: "once" # 自动白平衡：once/continuous/off

    camera_fx: 2594.8668197346 # 相机矩阵 X 方向焦距
    camera_fy: 2593.9303479068 # 相机矩阵 Y 方向焦距
    camera_cx: 623.6194463792 # 主点 X 坐标
    camera_cy: 487.9543574800 # 主点 Y 坐标

    dist_k1: 0.0013295332 # 径向畸变系数 k1
    dist_k2: -0.3225360920 # 径向畸变系数 k2
    dist_p1: 0.0008215090 # 切向畸变系数 p1
    dist_p2: 0.0001941072 # 切向畸变系数 p2
    dist_k3: 7.0936030151 # 径向畸变系数 k3
