aim_armor_decider_node:
  ros__parameters:
    front_0_target_states_topic: /aim_predictor/front_0/target_states
    front_1_target_states_topic: /aim_predictor/front_1/target_states
    back_target_states_topic: /aim_predictor/back/target_states
    outpost_state_topic: /aim_outpost_predictor/outpost_state
    armor_targets_topic: /ly/aim/armor_targets
    select_target_topic: /ly/aim/select_target
    selected_target_id_topic: /decider/selected_target_id
    select_target_timeout_sec: 0.5
    outpost_target_id: 6
