# sentry_tf?? /ly/gimbal/angles ?? TF ?
#   base_link --(yaw)--> gimbal_small_yaw --(yaw inverse)--> gimbal_world
#   gimbal_small_yaw --static(+Z)--> gimbal_barrel_joint --(pitch)--> gimbal_barrel
# ????yaw ?????pitch ????
sentry_tf_node:
  ros__parameters:
    gimbal_topic: "/ly/gimbal/angles"
    base_frame: "base_link"
    world_frame: "gimbal_world"
    yaw_frame: "gimbal_small_yaw"
    barrel_joint_frame: "gimbal_barrel_joint"
    barrel_frame: "gimbal_barrel"
    # ????barrel_joint??? yaw ???? +Z ??????????? TF ??
    barrel_offset_z: 0.320

# gimbal_barrel -> gx_camera_0 ?? TF????????
barrel_to_camera_0:
  x: 0.21932353
  y: 0.04072862
  z: -0.00025174
  yaw: -0.00603267
  pitch: -0.05759101
  roll: 0.03382602
  parent_frame: "gimbal_barrel"
  child_frame: "gx_camera_0"

# gimbal_barrel -> gx_camera_1 ?? TF????????
barrel_to_camera_1:
  x: 0.16924172
  y: -0.03997236
  z: 0.00414103
  yaw: 0.00857482
  pitch: -0.03424477
  roll: 0.00148875
  parent_frame: "gimbal_barrel"
  child_frame: "gx_camera_1"

small_yaw_to_usb_camera:
  x: 0.02135332
  y: -0.04887805
  z: 0.00000000
  yaw: 2.00145620
  pitch: 0.01951835
  roll: -0.00752812
  parent_frame: "gimbal_small_yaw"
  child_frame: "usb_camera"
